# Generated by Django 3.0.4 on 2021-06-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='icon',
            field=models.CharField(blank=True, max_length=20, verbose_name='Icono'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Titulo'),
        ),
    ]
