# Generated by Django 3.0.4 on 2021-07-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210629_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id_social_media', models.AutoField(primary_key=True, serialize=False)),
                ('icon', models.CharField(max_length=20, verbose_name='Icono')),
                ('social_url', models.URLField(unique=True, verbose_name='Url Social')),
            ],
            options={
                'verbose_name': 'Social media',
                'verbose_name_plural': 'Social Medias',
                'ordering': ['id_social_media'],
            },
        ),
    ]
