# Generated by Django 3.0.4 on 2021-07-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_socialmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='name',
            field=models.CharField(default=-2031, max_length=50, verbose_name='Nombre red social'),
            preserve_default=False,
        ),
    ]
