from django.db import models
from .modelos.model_contact import *
from .modelos.model_social_media import *
from .modelos.model_service import *
from .modelos.model_category import *
from .modelos.model_client import *
from .modelos.model_portfolio import *
from .modelos.model_testimonial import *
from .modelos.model_skills import *